name: release-plain

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_platform: [linux, linuxmusl,darwin]
        target_arch: [x64, arm64]

    
    steps:
    - name: Clone Main Repository
      uses: actions/checkout@v4
      with:
          repository: 'NapNeko/NapCat'
          token: ${{ secrets.NAPCAT_BUILD }}
    - name: Use Node.js 20.X
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Build NuCat Linux
      run: |
          npm install sqlite3 --target_arch=${{ matrix.target_arch }} --target_platform=${{ matrix.target_platform }} 
          npm run build
          zip NapCat.zip -r ./dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NapCat.${{ matrix.target_platform }}.${{ matrix.target_arch }}.zip
        path: NapCat.zip