name: release-plain

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_platform: [linux,darwin]
        target_arch: [x64, arm64]
    steps:
    - name: Clone Main Repository
      uses: actions/checkout@v4
      with:
          repository: 'NapNeko/NapCat'
          submodules: true
          token: ${{ secrets.NAPCAT_BUILD }}
    - name: Use Node.js 20.X
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Build NuCat Linux
      run: |
          npm i --arch=${{ matrix.target_arch }} --platform=${{ matrix.target_platform }} 
          npm run build:prod
          cd dist
          npm i --omit=dev
          cd ..
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NapCat.${{ matrix.target_platform }}.${{ matrix.target_arch }}
        path: dist
  build-win32:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_platform: [win32]
        target_arch: [x64]
    steps:
        - name: Clone Main Repository
          uses: actions/checkout@v4
          with:
                repository: 'NapNeko/NapCat'
                submodules: true
                token: ${{ secrets.NAPCAT_BUILD }}
        - name: Use Node.js 20.X
          uses: actions/setup-node@v4
          with:
              node-version: 20.x
        - name: Build NuCat Linux
          run: |
                npm i --arch=${{ matrix.target_arch }} --platform=${{ matrix.target_platform }} 
                npm run build:prod
                cd dist
                npm i --omit=dev
                cd ..
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
              name: NapCat.${{ matrix.target_platform }}.${{ matrix.target_arch }}
              path: dist
